last_change = 2026-09-09T17:44:55.377417Z
addr = 0x16b77f0
size = 0x62b
name = "CGameEventManager_UnserializeEvent"

[header]
name = "CGameEventManager_UnserializeEvent"
addr = 0x16b77f0

[header.args]
