last_change = 2026-09-10T03:40:17.901243Z
addr = 0x16b77f0
size = 0x62b
name = "CGameEventManager_UnserializeEvent"

[header]
name = "CGameEventManager_UnserializeEvent"
addr = 0x16b77f0

[header.args]
