last_change = 2026-09-09T16:17:05.931043Z
addr = 0x1711900
size = 0x10
name = "CGameSystemReallocatingFactory_CSource2EntitySystem_Init"

[header]
name = "CGameSystemReallocatingFactory_CSource2EntitySystem_Init"
addr = 0x1711900

[header.args]
