last_change = 2026-09-09T16:17:05.931124Z
addr = 0x1978b00
size = 0x18eb
name = "CPrediction_PostNetworkDataReceived"

[header]
name = "CPrediction_PostNetworkDataReceived"
addr = 0x1978b00

[header.args]
