last_change = 2026-09-09T16:17:05.931139Z
addr = 0x2e1a500
size = 0x10
name = "CEntitySystem_PostCreateEntitySystem"

[header]
name = "CEntitySystem_PostCreateEntitySystem"
addr = 0x2e1a500

[header.args]
